<template>
	<div>
		<section class="py-5 bg-white">
			<div class="container flex flex-col flex-wrap items-center justify-between py-5 mx-auto md:flex-row">
				<div class="relative flex flex-col md:flex-row">
					<a href="https://nano.besoeasy.com" class="flex items-center mb-5 font-medium text-gray-900 lg:w-auto lg:items-center lg:justify-center md:mb-0">
						<span class="mx-auto text-xl font-black leading-none text-gray-900 select-none">NANO.BESOEASY.COM</span>
					</a>
				</div>

				<div class="inline-flex items-center ml-5 space-x-6 lg:justify-end">
					<nav class="flex flex-wrap items-center mb-5 text-base md:mb-0 md:pl-8 md:ml-8 md:border-l md:border-gray-200">
						<a :href="'https://nanocrawler.cc/explorer/account/' + gameaddress" class="mr-5 font-medium leading-6 text-gray-600 hover:text-gray-900 uppercase">Explorer</a>
						<a :href="'https://github.com/besoeasy/simple-nano-game?' + gameaddress" class="mr-5 font-medium leading-6 text-gray-600 hover:text-gray-900 uppercase">Github</a>
					</nav>
				</div>
			</div>
		</section>

		<section class="text-gray-600 body-font">
			<div class="container mx-auto flex px-5 py-10 items-center justify-center flex-col">
				<img class="mb-10 object-cover object-center rounded" alt="hero" src="https://bafybeihq6dnwimqahij2ocihgdeihg7ctxu3a37whdiezb43sqdnetyctq.ipfs.infura-ipfs.io/" />
				<div class="text-center lg:w-2/3 w-full">
					<h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">DEPOSIT NANO TO PLAY !</h1>
					<p class="mb-8 leading-relaxed">
						{{ gameaddress }}
					</p>
					<div class="flex justify-center">
						<a :href="'nano:' + gameaddress" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Open Natrium</a>
					</div>
				</div>
			</div>
		</section>

		<section class="py-10 overflow-hidden">
			<div class="container mx-auto">
				<div class="grid grid-cols-1 gap-0 text-gray-600 md:grid-cols-4 md:gap-10">
					<div>
						<h5 class="mt-10 mb-3 text-lg font-bold font-heading text-gray-900">Roll Below 49</h5>
						<p>To win you must <strong>Roll Below 49</strong>. Rolls are generated by NANO block hashes.</p>
					</div>
					<div>
						<h5 class="mt-10 mb-3 text-lg font-bold font-heading text-gray-900">Win 2X</h5>
						<p>All winning bets get 2 times deposit amount, No logins required.</p>
					</div>
					<div>
						<h5 class="mt-10 mb-3 text-lg font-bold font-heading text-gray-900">Max Win</h5>
						<p>
							Maximum Win Per Bet is <strong>{{ formatS(balance / 10) }} NANO</strong>, you can't win more than this per bet.
						</p>
					</div>
					<div>
						<h5 class="mt-10 mb-3 text-lg font-bold font-heading text-gray-900">Game Balance</h5>
						<p>
							Game Balance is <strong>{{ formatS(balance) }} NANO</strong>, this will grow over time.
						</p>
					</div>
				</div>
			</div>
		</section>

		<section class="py-10 overflow-hidden">
			<div class="container mx-auto">
				<div class="overflow-x-auto">
					<table class="table w-full table-zebra">
						<thead>
							<tr>
								<th></th>
								<th>Player</th>
								<th>Amount</th>
								<th>Roll</th>
								<th>Type</th>
								<th>Block</th>
							</tr>
						</thead>
						<tbody>
							<tr v-for="item in betsdata" v-bind:key="item.id">
								<th>
									{{ item.height }}
								</th>
								<td>
									{{ item.account }}
								</td>
								<td>
									{{ item.amount }}
								</td>
								<td>
									<div v-if="item.type == 'receive'">{{ item.roll }}</div>
									<div v-if="item.type !== 'receive'">--</div>
								</td>
								<td>
									<a v-if="item.type == 'send'" class="px-4 py-1 text-red-400 rounded">SEND</a>
									<a v-if="item.type == 'receive'" class="px-4 py-1 text-green-400 rounded ">RECEIVE</a>
								</td>
								<td>
									<a target="_blank" class="px-4 py-1 text-white bg-blue-400 rounded" v-bind:href="'https://nanocrawler.cc/explorer/block/' + item.hash">View</a>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</section>

		<footer class="p-10 footer bg-base-200 text-base-content footer-center">
			<div>
				<a class="link link-hover" href="https://besoeasy.com"><p>© BESOEASY.COM</p></a>
			</div>
		</footer>
	</div>
</template>

<script>
	import { gameaddress, fetchData, accountfetchData, hashtoroll } from './func';

	export default {
		data() {
			return {
				fetching: true,
				gameaddress: gameaddress,
				balance: 0,
				betsdata: [],
			};
		},
		methods: {
			formatS: function(var1) {
				return parseFloat(var1 / 1000000000000000000000000000000).toFixed(8);
			},
			async fetchdata() {
				this.fetching = false;

				console.log('fetching data');

				const accountdata = await accountfetchData();

				const data = await fetchData();

				const history = data.history;

				this.balance = accountdata.balance;

				this.betsdata = [];

				var i;

				for (i = 0; i < history.length; i++) {
					var roll = await hashtoroll(history[i].hash);

					var obj = {
						height: history[i].height,
						account: history[i].account,
						amount: this.formatS(history[i].amount),
						type: history[i].type,
						hash: history[i].hash,
						roll: roll,
					};

					this.betsdata.push(obj);
				}

				this.fetching = true;
			},
		},
		async mounted() {
			setInterval(async () => {
				if (this.fetching) {
					this.fetchdata();
				}
			}, 5000);
		},
	};
</script>
